version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - canonicalheader
    - copyloopvar
    #- cyclop
    #- funlen
    #- gocognit
    #- gocyclo
    - maintidx
    #- nestif
    #- lll
    - decorder
    - dupword
    - durationcheck
    - errname
    - gosmopolitan
    - misspell
    - predeclared
    - sloglint
    - staticcheck
  disable:
    - errcheck
formatters:
  enable:
    - gofmt
