FROM --platform=$BUILDPLATFORM golang:1-alpine AS builder
ARG TARGETARCH
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOARCH=$TARGETARCH go build -o ziphttp .

FROM scratch
COPY --from=builder /build/ziphttp /ziphttp
ENTRYPOINT ["/ziphttp"]
