name: docker

on:
  push:
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wtnb75/actions/docker@main
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
