name: update go.mod

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update_deps:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
      - run: go get -u
      - run: go mod tidy
      - name: lint
        uses: golangci/golangci-lint-action@v6
      - name: test
        run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Dependencies
          title: 'auto update dependencies'
          add-paths: |
             go.mod
             go.sum
